# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omachy < Formula
  desc "Tiling window manager setup for macOS"
  homepage "https://dough654.github.io/Omachy/"
  version "0.1.4-alpha"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dough654/Omachy/releases/download/v0.1.4-alpha/omachy_0.1.4-alpha_darwin_amd64.tar.gz"
    sha256 "9905724eec7c59e523dce4b2b7858d6ccd8eda7a1d5292f1f4040f0220e0b395"

    define_method(:install) do
      bin.install "omachy"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dough654/Omachy/releases/download/v0.1.4-alpha/omachy_0.1.4-alpha_darwin_arm64.tar.gz"
    sha256 "683d97b20b8a3d7a37eb29bfaeb79fd9fabbdcf6a5ab2ec0fe0025f460cb8747"

    define_method(:install) do
      bin.install "omachy"
    end
  end

  test do
    system "#{bin}/omachy", "version"
  end
end
