# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omachy < Formula
  desc "Tiling window manager setup for macOS"
  homepage "https://dough654.github.io/Omachy/"
  version "0.1.1-alpha"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dough654/Omachy/releases/download/v0.1.1-alpha/omachy_0.1.1-alpha_darwin_amd64.tar.gz"
    sha256 "99df3affc5084e7fd4686e1a1aa8521c1cfc565241a753675570b57aa0018d09"

    define_method(:install) do
      bin.install "omachy"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dough654/Omachy/releases/download/v0.1.1-alpha/omachy_0.1.1-alpha_darwin_arm64.tar.gz"
    sha256 "1256513818ed4add853be4e55d7a526017ecb5ce4eb21309de7693562655f7f4"

    define_method(:install) do
      bin.install "omachy"
    end
  end

  test do
    system "#{bin}/omachy", "version"
  end
end
