# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Omachy < Formula
  desc "Tiling window manager setup for macOS"
  homepage "https://dough654.github.io/Omachy/"
  version "0.1.5-alpha"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/dough654/Omachy/releases/download/v0.1.5-alpha/omachy_0.1.5-alpha_darwin_amd64.tar.gz"
    sha256 "c0caace42abffbe8bbc6f4573d97c70b0aa0e64a001b5de6a54bdfcdada93fe8"

    define_method(:install) do
      bin.install "omachy"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/dough654/Omachy/releases/download/v0.1.5-alpha/omachy_0.1.5-alpha_darwin_arm64.tar.gz"
    sha256 "ffcf06f14cd2bef0b7b943ffcaddeb87dea15e0fc60a6103cef9e2bd96a8fb47"

    define_method(:install) do
      bin.install "omachy"
    end
  end

  test do
    system "#{bin}/omachy", "version"
  end
end
